---
#
# SPDX-License-Identifier: GPL-3.0-or-later

default:
  image: "archlinux:latest"

variables:
  BUILD_SCRIPT: ./.gitlab/ci/build-inside-vm.sh
  QEMU_BUILD_TIMEOUT: 2400
  QEMU_VM_MEMORY: 3072
  ARCHISO_COW_SPACE_SIZE: 2g

stages:
  - lint
  - build

shellcheck:
  stage: lint
  before_script:
    - pacman --noconfirm -Syu --needed make shellcheck
  script:
    - make lint

.build:
  variables:
    PACKAGE_LIST: dosfstools e2fsprogs erofs-utils jq libisoburn mtools openssl qemu-headless squashfs-tools zsync
  stage: build
  before_script:
    - pacman -Syu --needed --noconfirm qemu-headless
  script:
    - ./.gitlab/ci/build-host.sh
  after_script:
    - PROFILE=($BUILD_SCRIPT_ARGS) && cp -- "output/${PROFILE[0]}/metrics.txt" .
  artifacts:
    name: "output"
    paths:
      - "output/*/*"
    expire_in: 2d
    reports:
      metrics: metrics.txt

build_short:
  extends: .build
  parallel:
    matrix:
      # baseline does not support netboot with codesinging
      # https://gitlab.archlinux.org/archlinux/archiso/-/issues/132
      - BUILD_SCRIPT_ARGS: baseline bootstrap
      - BUILD_SCRIPT_ARGS: releng bootstrap

build_long:
  extends: .build
  tags:
    - fast-single-thread
  parallel:
    matrix:
      - BUILD_SCRIPT_ARGS: baseline iso
      - BUILD_SCRIPT_ARGS: releng iso
      - BUILD_SCRIPT_ARGS: releng netboot
