#!/bin/bash

bell=0
pause=0
root=0
telnet=0
options=0

# if there's an issue with the command, print usage
if [ "$*" == "" ] ; then
	echo "Usage: ifup [-bprt] [host to ping] [command to execute]"
	exit 1
else

	# if options are passed, parse them
	if [[  $1 =~ - ]] ; then
		if [[ $1 =~ b ]] ; then
			bell=1
		fi
		if [[ $1 =~ p ]] ; then
			pause=1
		fi
		if [[ $1 =~ r ]] ; then
			root=1
		fi
		if [[ $1 =~ t ]] ; then
			telnet=1
		fi
		shift
	fi

	# parse address or hostname to ping
	ping=$1
	shift

	# if no command given, assume ssh the address or hostname
	if [ "$*" == "" ] ; then
		if [ "$root" == "1" ] ; then
			if [ "$telnet" == "1" ] ; then
				echo "Error: -r option and -t option should not be used together"
				exit 1
			fi
			run="ssh root@$ping"
		elif [ "$telnet" == "1" ] ; then
			run="telnet $ping"
		else
			run="ssh $ping"
		fi
	else
		if [ "$root" == "1" ] ; then
			echo "Error: -r option should not be used with an explicit command"
			exit 1
		elif [ "$telnet" == "1" ] ; then
			echo "Error: -t option should not be used with an explicit command"
			exit 1
		else
			run=$*
		fi
	fi
fi

ipup=0
numtries=0
while [ "$ipup" -eq "0" ] ; do
	ping -w 2 $ping && ipup=1
	sleep 1
	numtries=$(($numtries+1))
	if [ "$numtries" -ge "3" ] ; then
		echo "No response after three tries, quitting"
		exit 1
	fi
done
# if we should pause, pause
if [ "$pause" == "1" ] ; then
	echo sleeping for 30 seconds . . .
	sleep 30
fi
# if we should bell, bell
if [ "$bell" == "1" ] ; then
	~/.bin/bell
fi
$run
